# vim:sw=2:et:

sudo: false
language: erlang
notifications:
  email:
    - alerts@rabbitmq.com
addons:
  apt:
    packages:
      - awscli
      - xsltproc
cache:
  apt: true
env:
  global:
    - secure: dNe7/M6y+L1jNh2QSfp4QtzBuF/1W9IvWTuLXwqEuneF9vP9XRYBEHTOVkfgizjYLMQrhpkajsxTTbRd5qEvaJVzvRyhx5nQjbTLoINHk1saFP7ZmMj+K4F6ogA6TubcL788kh6cl/6lvBLtqpi4X8noOBR0e3MNlIK0Doz0qHU=
    - secure: fOmMCkk0Z/+2gzFp/DXlQ7bycBclMpryber+0r5CFfgIoeT+OnNqxhC8SXTMJw2UwTKAL9fhy5HXBu1Et3iBGhdp05NVC5T/UtsJt5RoRt2FVEb4OXyB3FDK3eI8LgiDCQcr1nCq9TapAPWJ8TCdGteCbwEPXeDcARpctwpAU7M=

otp_release:
  - "R16B03-1"
  - "19.3"
  - "20.1"

before_script:
  # The checkout made by Travis is a "detached HEAD" and branches
  # information is missing. Our Erlang.mk's git_rmq fetch method relies
  # on it, so we need to restore it.
  #
  # We simply fetch master and, if it exists, stable branches. A branch
  # is created, pointing to the detached HEAD.
  - |
    git checkout -B "${TRAVIS_TAG:-${TRAVIS_BRANCH}}"
    git remote add upstream https://github.com/$TRAVIS_REPO_SLUG.git
    git fetch upstream stable:stable || :
    git fetch upstream master:master || :

script:
  - make xref
  - make tests

after_failure:
  - |
    cd "$TRAVIS_BUILD_DIR"
    if test -d logs && test "$AWS_ACCESS_KEY_ID" && test "$AWS_SECRET_ACCESS_KEY"; then
      archive_name="$(basename "$TRAVIS_REPO_SLUG")-$TRAVIS_JOB_NUMBER"

      tar -c --transform "s/^logs/${archive_name}/" -f - logs | \
        xz > "${archive_name}.tar.xz"

      aws s3 cp "${archive_name}.tar.xz" s3://server-release-pipeline/travis-ci-logs/ \
        --region eu-west-1 \
        --acl public-read
    fi
