name: Workflow Base Images
on:
- workflow_dispatch
jobs:
  ci-base:
    name: ci-base
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        erlang_version:
        - "22.3"
        - "23.1"
      fail-fast: false
    steps:
    - name: CHECKOUT REPOSITORY
      uses: actions/checkout@v2
    - name: CREATE ERLANG+ELIXIR IMAGE (${{ matrix.erlang_version }})
      uses: docker/build-push-action@v1
      with:
        username: _json_key
        password: ${{ secrets.GCR_JSON_KEY }}
        registry: eu.gcr.io
        repository: cf-rabbitmq-core/erlang_elixir
        dockerfile: ci/dockerfiles/${{ matrix.erlang_version }}/erlang_elixir
        tags: ${{ matrix.erlang_version }}
    - name: CREATE BASE CI IMAGE (${{ matrix.erlang_version }})
      uses: docker/build-push-action@v1
      with:
        username: _json_key
        password: ${{ secrets.GCR_JSON_KEY }}
        registry: eu.gcr.io
        repository: cf-rabbitmq-core/ci-base
        dockerfile: ci/dockerfiles/ci-base
        build_args: ERLANG_VERSION=${{ matrix.erlang_version }},SECONDARY_UMBRELLA_GITREFS=v3.7.28 v3.8.9
        tags: ${{ matrix.erlang_version }}
