name: Maintenance
on:
  schedule:
  - cron: '0 2 * * *'
  workflow_dispatch:
jobs:
  cleanup-ci-images:
    name: cleanup-ci-images
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        image:
        - ci
        - ci-rabbit
    steps:
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCR_JSON_KEY }}
        export_default_credentials: true
    - run: |
        gcloud auth configure-docker
    - name: CLEAN OLD ${{ matrix.image }} IMAGES
      env:
        IMAGE: eu.gcr.io/cf-rabbitmq-core/${{ matrix.image }}
      run: |
        DATE=$(date -d "-1 week" '+%Y-%m-%d')
        C=0
        for digest in $(gcloud container images list-tags ${IMAGE} --limit=999999 --sort-by=TIMESTAMP \
          --filter="timestamp.datetime < '${DATE}'" --format='get(digest)'); do
          (
            set -x
            gcloud container images delete -q --force-delete-tags "${IMAGE}@${digest}"
          )
          C=$(expr $C + 1)
        done
        echo "Deleted ${C} images in ${IMAGE}." >&2
